//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.action.ActionElement;
import org.omg.schema.spec.kdm._1_1.core.KDMEntity;


/**
 * <p>Java class for DataAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataAction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/data}AbstractDataElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="implementation" type="{http://schema.omg.org/spec/KDM/1.1/action}ActionElement"/>
 *         &lt;element name="dataElement" type="{http://schema.omg.org/spec/KDM/1.1/data}DataEvent"/>
 *       &lt;/choice>
 *       &lt;attribute name="kind" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="implementation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataAction", propOrder = {
    "implementationOrDataElement"
})
public class DataAction
    extends AbstractDataElement
{

    @XmlElements({
        @XmlElement(name = "implementation", type = ActionElement.class),
        @XmlElement(name = "dataElement", type = DataEvent.class)
    })
    protected List<KDMEntity> implementationOrDataElement;
    @XmlAttribute
    protected String kind;
    @XmlAttribute
    protected String implementation;

    /**
     * Gets the value of the implementationOrDataElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the implementationOrDataElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImplementationOrDataElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionElement }
     * {@link DataEvent }
     * 
     * 
     */
    public List<KDMEntity> getImplementationOrDataElement() {
        if (implementationOrDataElement == null) {
            implementationOrDataElement = new ArrayList<KDMEntity>();
        }
        return this.implementationOrDataElement;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKind(String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

}
