//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReadsColumnSet_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ReadsColumnSet");
    private final static QName _ContentReference_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ContentReference");
    private final static QName _UniqueKey_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "UniqueKey");
    private final static QName _KeyRelation_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "KeyRelation");
    private final static QName _DataAction_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataAction");
    private final static QName _IndexElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "IndexElement");
    private final static QName _SimpleContentType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "SimpleContentType");
    private final static QName _MixedContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "MixedContent");
    private final static QName _ComplexContentType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ComplexContentType");
    private final static QName _TypedBy_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "TypedBy");
    private final static QName _HasContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "HasContent");
    private final static QName _DatatypeOf_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DatatypeOf");
    private final static QName _XMLSchema_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "XMLSchema");
    private final static QName _ContentRestriction_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ContentRestriction");
    private final static QName _ExtendedDataElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ExtendedDataElement");
    private final static QName _DataRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataRelationship");
    private final static QName _RestrictionOf_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "RestrictionOf");
    private final static QName _ManagesData_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ManagesData");
    private final static QName _ContentElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ContentElement");
    private final static QName _SeqContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "SeqContent");
    private final static QName _RelationalView_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "RelationalView");
    private final static QName _DataModel_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataModel");
    private final static QName _RelationalSchema_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "RelationalSchema");
    private final static QName _GroupContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "GroupContent");
    private final static QName _DataResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataResource");
    private final static QName _AbstractContentElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "AbstractContentElement");
    private final static QName _DataContainer_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataContainer");
    private final static QName _ColumnSet_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ColumnSet");
    private final static QName _WritesColumnSet_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "WritesColumnSet");
    private final static QName _RelationalTable_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "RelationalTable");
    private final static QName _ContentItem_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ContentItem");
    private final static QName _ChoiceContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ChoiceContent");
    private final static QName _ExtensionTo_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ExtensionTo");
    private final static QName _ContentAttribute_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ContentAttribute");
    private final static QName _DataSegment_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataSegment");
    private final static QName _ReferenceTo_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ReferenceTo");
    private final static QName _ReferenceKey_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ReferenceKey");
    private final static QName _AllContent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "AllContent");
    private final static QName _DataEvent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "DataEvent");
    private final static QName _Catalog_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "Catalog");
    private final static QName _RecordFile_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "RecordFile");
    private final static QName _AbstractDataElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "AbstractDataElement");
    private final static QName _ProducesDataEvent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "ProducesDataEvent");
    private final static QName _Index_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "Index");
    private final static QName _AbstractDataRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/data", "AbstractDataRelationship");
    private final static QName _RestrictionOfTo_QNAME = new QName("", "to");
    private final static QName _RestrictionOfFrom_QNAME = new QName("", "from");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLSchema }
     * 
     */
    public XMLSchema createXMLSchema() {
        return new XMLSchema();
    }

    /**
     * Create an instance of {@link ExtensionTo }
     * 
     */
    public ExtensionTo createExtensionTo() {
        return new ExtensionTo();
    }

    /**
     * Create an instance of {@link ComplexContentType }
     * 
     */
    public ComplexContentType createComplexContentType() {
        return new ComplexContentType();
    }

    /**
     * Create an instance of {@link ManagesData }
     * 
     */
    public ManagesData createManagesData() {
        return new ManagesData();
    }

    /**
     * Create an instance of {@link TypedBy }
     * 
     */
    public TypedBy createTypedBy() {
        return new TypedBy();
    }

    /**
     * Create an instance of {@link DataRelationship }
     * 
     */
    public DataRelationship createDataRelationship() {
        return new DataRelationship();
    }

    /**
     * Create an instance of {@link MixedContent }
     * 
     */
    public MixedContent createMixedContent() {
        return new MixedContent();
    }

    /**
     * Create an instance of {@link SimpleContentType }
     * 
     */
    public SimpleContentType createSimpleContentType() {
        return new SimpleContentType();
    }

    /**
     * Create an instance of {@link ColumnSet }
     * 
     */
    public ColumnSet createColumnSet() {
        return new ColumnSet();
    }

    /**
     * Create an instance of {@link UniqueKey }
     * 
     */
    public UniqueKey createUniqueKey() {
        return new UniqueKey();
    }

    /**
     * Create an instance of {@link RestrictionOf }
     * 
     */
    public RestrictionOf createRestrictionOf() {
        return new RestrictionOf();
    }

    /**
     * Create an instance of {@link RecordFile }
     * 
     */
    public RecordFile createRecordFile() {
        return new RecordFile();
    }

    /**
     * Create an instance of {@link KeyRelation }
     * 
     */
    public KeyRelation createKeyRelation() {
        return new KeyRelation();
    }

    /**
     * Create an instance of {@link ReferenceKey }
     * 
     */
    public ReferenceKey createReferenceKey() {
        return new ReferenceKey();
    }

    /**
     * Create an instance of {@link ContentItem }
     * 
     */
    public ContentItem createContentItem() {
        return new ContentItem();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link DataContainer }
     * 
     */
    public DataContainer createDataContainer() {
        return new DataContainer();
    }

    /**
     * Create an instance of {@link ReferenceTo }
     * 
     */
    public ReferenceTo createReferenceTo() {
        return new ReferenceTo();
    }

    /**
     * Create an instance of {@link GroupContent }
     * 
     */
    public GroupContent createGroupContent() {
        return new GroupContent();
    }

    /**
     * Create an instance of {@link ProducesDataEvent }
     * 
     */
    public ProducesDataEvent createProducesDataEvent() {
        return new ProducesDataEvent();
    }

    /**
     * Create an instance of {@link ContentRestriction }
     * 
     */
    public ContentRestriction createContentRestriction() {
        return new ContentRestriction();
    }

    /**
     * Create an instance of {@link DataResource }
     * 
     */
    public DataResource createDataResource() {
        return new DataResource();
    }

    /**
     * Create an instance of {@link ReadsColumnSet }
     * 
     */
    public ReadsColumnSet createReadsColumnSet() {
        return new ReadsColumnSet();
    }

    /**
     * Create an instance of {@link IndexElement }
     * 
     */
    public IndexElement createIndexElement() {
        return new IndexElement();
    }

    /**
     * Create an instance of {@link RelationalTable }
     * 
     */
    public RelationalTable createRelationalTable() {
        return new RelationalTable();
    }

    /**
     * Create an instance of {@link ChoiceContent }
     * 
     */
    public ChoiceContent createChoiceContent() {
        return new ChoiceContent();
    }

    /**
     * Create an instance of {@link RelationalView }
     * 
     */
    public RelationalView createRelationalView() {
        return new RelationalView();
    }

    /**
     * Create an instance of {@link HasContent }
     * 
     */
    public HasContent createHasContent() {
        return new HasContent();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link ContentElement }
     * 
     */
    public ContentElement createContentElement() {
        return new ContentElement();
    }

    /**
     * Create an instance of {@link ContentAttribute }
     * 
     */
    public ContentAttribute createContentAttribute() {
        return new ContentAttribute();
    }

    /**
     * Create an instance of {@link WritesColumnSet }
     * 
     */
    public WritesColumnSet createWritesColumnSet() {
        return new WritesColumnSet();
    }

    /**
     * Create an instance of {@link SeqContent }
     * 
     */
    public SeqContent createSeqContent() {
        return new SeqContent();
    }

    /**
     * Create an instance of {@link DataEvent }
     * 
     */
    public DataEvent createDataEvent() {
        return new DataEvent();
    }

    /**
     * Create an instance of {@link ExtendedDataElement }
     * 
     */
    public ExtendedDataElement createExtendedDataElement() {
        return new ExtendedDataElement();
    }

    /**
     * Create an instance of {@link RelationalSchema }
     * 
     */
    public RelationalSchema createRelationalSchema() {
        return new RelationalSchema();
    }

    /**
     * Create an instance of {@link DataModel }
     * 
     */
    public DataModel createDataModel() {
        return new DataModel();
    }

    /**
     * Create an instance of {@link AllContent }
     * 
     */
    public AllContent createAllContent() {
        return new AllContent();
    }

    /**
     * Create an instance of {@link DatatypeOf }
     * 
     */
    public DatatypeOf createDatatypeOf() {
        return new DatatypeOf();
    }

    /**
     * Create an instance of {@link DataAction }
     * 
     */
    public DataAction createDataAction() {
        return new DataAction();
    }

    /**
     * Create an instance of {@link ContentReference }
     * 
     */
    public ContentReference createContentReference() {
        return new ContentReference();
    }

    /**
     * Create an instance of {@link DataSegment }
     * 
     */
    public DataSegment createDataSegment() {
        return new DataSegment();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadsColumnSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ReadsColumnSet")
    public JAXBElement<ReadsColumnSet> createReadsColumnSet(ReadsColumnSet value) {
        return new JAXBElement<ReadsColumnSet>(_ReadsColumnSet_QNAME, ReadsColumnSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ContentReference")
    public JAXBElement<ContentReference> createContentReference(ContentReference value) {
        return new JAXBElement<ContentReference>(_ContentReference_QNAME, ContentReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UniqueKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "UniqueKey")
    public JAXBElement<UniqueKey> createUniqueKey(UniqueKey value) {
        return new JAXBElement<UniqueKey>(_UniqueKey_QNAME, UniqueKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyRelation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "KeyRelation")
    public JAXBElement<KeyRelation> createKeyRelation(KeyRelation value) {
        return new JAXBElement<KeyRelation>(_KeyRelation_QNAME, KeyRelation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataAction")
    public JAXBElement<DataAction> createDataAction(DataAction value) {
        return new JAXBElement<DataAction>(_DataAction_QNAME, DataAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "IndexElement")
    public JAXBElement<IndexElement> createIndexElement(IndexElement value) {
        return new JAXBElement<IndexElement>(_IndexElement_QNAME, IndexElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "SimpleContentType")
    public JAXBElement<SimpleContentType> createSimpleContentType(SimpleContentType value) {
        return new JAXBElement<SimpleContentType>(_SimpleContentType_QNAME, SimpleContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "MixedContent")
    public JAXBElement<MixedContent> createMixedContent(MixedContent value) {
        return new JAXBElement<MixedContent>(_MixedContent_QNAME, MixedContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ComplexContentType")
    public JAXBElement<ComplexContentType> createComplexContentType(ComplexContentType value) {
        return new JAXBElement<ComplexContentType>(_ComplexContentType_QNAME, ComplexContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedBy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "TypedBy")
    public JAXBElement<TypedBy> createTypedBy(TypedBy value) {
        return new JAXBElement<TypedBy>(_TypedBy_QNAME, TypedBy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "HasContent")
    public JAXBElement<HasContent> createHasContent(HasContent value) {
        return new JAXBElement<HasContent>(_HasContent_QNAME, HasContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatatypeOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DatatypeOf")
    public JAXBElement<DatatypeOf> createDatatypeOf(DatatypeOf value) {
        return new JAXBElement<DatatypeOf>(_DatatypeOf_QNAME, DatatypeOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLSchema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "XMLSchema")
    public JAXBElement<XMLSchema> createXMLSchema(XMLSchema value) {
        return new JAXBElement<XMLSchema>(_XMLSchema_QNAME, XMLSchema.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ContentRestriction")
    public JAXBElement<ContentRestriction> createContentRestriction(ContentRestriction value) {
        return new JAXBElement<ContentRestriction>(_ContentRestriction_QNAME, ContentRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedDataElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ExtendedDataElement")
    public JAXBElement<ExtendedDataElement> createExtendedDataElement(ExtendedDataElement value) {
        return new JAXBElement<ExtendedDataElement>(_ExtendedDataElement_QNAME, ExtendedDataElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataRelationship")
    public JAXBElement<DataRelationship> createDataRelationship(DataRelationship value) {
        return new JAXBElement<DataRelationship>(_DataRelationship_QNAME, DataRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RestrictionOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "RestrictionOf")
    public JAXBElement<RestrictionOf> createRestrictionOf(RestrictionOf value) {
        return new JAXBElement<RestrictionOf>(_RestrictionOf_QNAME, RestrictionOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagesData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ManagesData")
    public JAXBElement<ManagesData> createManagesData(ManagesData value) {
        return new JAXBElement<ManagesData>(_ManagesData_QNAME, ManagesData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ContentElement")
    public JAXBElement<ContentElement> createContentElement(ContentElement value) {
        return new JAXBElement<ContentElement>(_ContentElement_QNAME, ContentElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeqContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "SeqContent")
    public JAXBElement<SeqContent> createSeqContent(SeqContent value) {
        return new JAXBElement<SeqContent>(_SeqContent_QNAME, SeqContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationalView }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "RelationalView")
    public JAXBElement<RelationalView> createRelationalView(RelationalView value) {
        return new JAXBElement<RelationalView>(_RelationalView_QNAME, RelationalView.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataModel")
    public JAXBElement<DataModel> createDataModel(DataModel value) {
        return new JAXBElement<DataModel>(_DataModel_QNAME, DataModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationalSchema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "RelationalSchema")
    public JAXBElement<RelationalSchema> createRelationalSchema(RelationalSchema value) {
        return new JAXBElement<RelationalSchema>(_RelationalSchema_QNAME, RelationalSchema.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "GroupContent")
    public JAXBElement<GroupContent> createGroupContent(GroupContent value) {
        return new JAXBElement<GroupContent>(_GroupContent_QNAME, GroupContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataResource")
    public JAXBElement<DataResource> createDataResource(DataResource value) {
        return new JAXBElement<DataResource>(_DataResource_QNAME, DataResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractContentElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "AbstractContentElement")
    public JAXBElement<AbstractContentElement> createAbstractContentElement(AbstractContentElement value) {
        return new JAXBElement<AbstractContentElement>(_AbstractContentElement_QNAME, AbstractContentElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataContainer")
    public JAXBElement<DataContainer> createDataContainer(DataContainer value) {
        return new JAXBElement<DataContainer>(_DataContainer_QNAME, DataContainer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColumnSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ColumnSet")
    public JAXBElement<ColumnSet> createColumnSet(ColumnSet value) {
        return new JAXBElement<ColumnSet>(_ColumnSet_QNAME, ColumnSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WritesColumnSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "WritesColumnSet")
    public JAXBElement<WritesColumnSet> createWritesColumnSet(WritesColumnSet value) {
        return new JAXBElement<WritesColumnSet>(_WritesColumnSet_QNAME, WritesColumnSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationalTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "RelationalTable")
    public JAXBElement<RelationalTable> createRelationalTable(RelationalTable value) {
        return new JAXBElement<RelationalTable>(_RelationalTable_QNAME, RelationalTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ContentItem")
    public JAXBElement<ContentItem> createContentItem(ContentItem value) {
        return new JAXBElement<ContentItem>(_ContentItem_QNAME, ContentItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChoiceContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ChoiceContent")
    public JAXBElement<ChoiceContent> createChoiceContent(ChoiceContent value) {
        return new JAXBElement<ChoiceContent>(_ChoiceContent_QNAME, ChoiceContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ExtensionTo")
    public JAXBElement<ExtensionTo> createExtensionTo(ExtensionTo value) {
        return new JAXBElement<ExtensionTo>(_ExtensionTo_QNAME, ExtensionTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentAttribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ContentAttribute")
    public JAXBElement<ContentAttribute> createContentAttribute(ContentAttribute value) {
        return new JAXBElement<ContentAttribute>(_ContentAttribute_QNAME, ContentAttribute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataSegment")
    public JAXBElement<DataSegment> createDataSegment(DataSegment value) {
        return new JAXBElement<DataSegment>(_DataSegment_QNAME, DataSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ReferenceTo")
    public JAXBElement<ReferenceTo> createReferenceTo(ReferenceTo value) {
        return new JAXBElement<ReferenceTo>(_ReferenceTo_QNAME, ReferenceTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ReferenceKey")
    public JAXBElement<ReferenceKey> createReferenceKey(ReferenceKey value) {
        return new JAXBElement<ReferenceKey>(_ReferenceKey_QNAME, ReferenceKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "AllContent")
    public JAXBElement<AllContent> createAllContent(AllContent value) {
        return new JAXBElement<AllContent>(_AllContent_QNAME, AllContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "DataEvent")
    public JAXBElement<DataEvent> createDataEvent(DataEvent value) {
        return new JAXBElement<DataEvent>(_DataEvent_QNAME, DataEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Catalog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "Catalog")
    public JAXBElement<Catalog> createCatalog(Catalog value) {
        return new JAXBElement<Catalog>(_Catalog_QNAME, Catalog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "RecordFile")
    public JAXBElement<RecordFile> createRecordFile(RecordFile value) {
        return new JAXBElement<RecordFile>(_RecordFile_QNAME, RecordFile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractDataElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "AbstractDataElement")
    public JAXBElement<AbstractDataElement> createAbstractDataElement(AbstractDataElement value) {
        return new JAXBElement<AbstractDataElement>(_AbstractDataElement_QNAME, AbstractDataElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducesDataEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "ProducesDataEvent")
    public JAXBElement<ProducesDataEvent> createProducesDataEvent(ProducesDataEvent value) {
        return new JAXBElement<ProducesDataEvent>(_ProducesDataEvent_QNAME, ProducesDataEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Index }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "Index")
    public JAXBElement<Index> createIndex(Index value) {
        return new JAXBElement<Index>(_Index_QNAME, Index.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractDataRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/data", name = "AbstractDataRelationship")
    public JAXBElement<AbstractDataRelationship> createAbstractDataRelationship(AbstractDataRelationship value) {
        return new JAXBElement<AbstractDataRelationship>(_AbstractDataRelationship_QNAME, AbstractDataRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = RestrictionOf.class)
    public JAXBElement<ComplexContentType> createRestrictionOfTo(ComplexContentType value) {
        return new JAXBElement<ComplexContentType>(_RestrictionOfTo_QNAME, ComplexContentType.class, RestrictionOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = RestrictionOf.class)
    public JAXBElement<ComplexContentType> createRestrictionOfFrom(ComplexContentType value) {
        return new JAXBElement<ComplexContentType>(_RestrictionOfFrom_QNAME, ComplexContentType.class, RestrictionOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = ExtensionTo.class)
    public JAXBElement<ComplexContentType> createExtensionToTo(ComplexContentType value) {
        return new JAXBElement<ComplexContentType>(_RestrictionOfTo_QNAME, ComplexContentType.class, ExtensionTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = ExtensionTo.class)
    public JAXBElement<ComplexContentType> createExtensionToFrom(ComplexContentType value) {
        return new JAXBElement<ComplexContentType>(_RestrictionOfFrom_QNAME, ComplexContentType.class, ExtensionTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = ReferenceTo.class)
    public JAXBElement<ContentItem> createReferenceToTo(ContentItem value) {
        return new JAXBElement<ContentItem>(_RestrictionOfTo_QNAME, ContentItem.class, ReferenceTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = ReferenceTo.class)
    public JAXBElement<ContentItem> createReferenceToFrom(ContentItem value) {
        return new JAXBElement<ContentItem>(_RestrictionOfFrom_QNAME, ContentItem.class, ReferenceTo.class, value);
    }

}
