//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.action.ActionElement;
import org.omg.schema.spec.kdm._1_1.code.AbstractCodeElement;
import org.omg.schema.spec.kdm._1_1.core.Element;
import org.omg.schema.spec.kdm._1_1.core.KDMEntity;
import org.omg.schema.spec.kdm._1_1.source.SourceRef;


/**
 * <p>Java class for AbstractUIElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractUIElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}KDMEntity">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="source" type="{http://schema.omg.org/spec/KDM/1.1/source}SourceRef"/>
 *         &lt;element name="UIRelation" type="{http://schema.omg.org/spec/KDM/1.1/ui}AbstractUIRelationship"/>
 *         &lt;element name="implementation" type="{http://schema.omg.org/spec/KDM/1.1/code}AbstractCodeElement"/>
 *         &lt;element name="abstraction" type="{http://schema.omg.org/spec/KDM/1.1/action}ActionElement"/>
 *       &lt;/choice>
 *       &lt;attribute name="implementation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractUIElement", propOrder = {
    "sourceOrUIRelationOrImplementation"
})
@XmlSeeAlso({
    UIElement.class,
    UIEvent.class,
    UIAction.class,
    UIResource.class
})
public abstract class AbstractUIElement
    extends KDMEntity
{

    @XmlElements({
        @XmlElement(name = "source", type = SourceRef.class),
        @XmlElement(name = "UIRelation", type = AbstractUIRelationship.class),
        @XmlElement(name = "abstraction", type = ActionElement.class),
        @XmlElement(name = "implementation", type = AbstractCodeElement.class)
    })
    protected List<Element> sourceOrUIRelationOrImplementation;
    @XmlAttribute
    protected String implementation;

    /**
     * Gets the value of the sourceOrUIRelationOrImplementation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOrUIRelationOrImplementation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOrUIRelationOrImplementation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceRef }
     * {@link AbstractUIRelationship }
     * {@link ActionElement }
     * {@link AbstractCodeElement }
     * 
     * 
     */
    public List<Element> getSourceOrUIRelationOrImplementation() {
        if (sourceOrUIRelationOrImplementation == null) {
            sourceOrUIRelationOrImplementation = new ArrayList<Element>();
        }
        return this.sourceOrUIRelationOrImplementation;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

}
