//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.ui;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.ui package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UIFlow_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIFlow");
    private final static QName _WritesUI_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "WritesUI");
    private final static QName _ReadsUI_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "ReadsUI");
    private final static QName _UIRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIRelationship");
    private final static QName _UIResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIResource");
    private final static QName _Screen_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "Screen");
    private final static QName _UIDisplay_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIDisplay");
    private final static QName _AbstractUIElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "AbstractUIElement");
    private final static QName _UIModel_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIModel");
    private final static QName _Report_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "Report");
    private final static QName _DisplaysImage_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "DisplaysImage");
    private final static QName _UIEvent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIEvent");
    private final static QName _UIField_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIField");
    private final static QName _UILayout_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UILayout");
    private final static QName _UIAction_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIAction");
    private final static QName _AbstractUIRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "AbstractUIRelationship");
    private final static QName _UIElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "UIElement");
    private final static QName _ManagesUI_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "ManagesUI");
    private final static QName _Displays_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/ui", "Displays");
    private final static QName _UILayoutTo_QNAME = new QName("", "to");
    private final static QName _UILayoutFrom_QNAME = new QName("", "from");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.ui
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UIAction }
     * 
     */
    public UIAction createUIAction() {
        return new UIAction();
    }

    /**
     * Create an instance of {@link UIElement }
     * 
     */
    public UIElement createUIElement() {
        return new UIElement();
    }

    /**
     * Create an instance of {@link UIModel }
     * 
     */
    public UIModel createUIModel() {
        return new UIModel();
    }

    /**
     * Create an instance of {@link UIEvent }
     * 
     */
    public UIEvent createUIEvent() {
        return new UIEvent();
    }

    /**
     * Create an instance of {@link UIFlow }
     * 
     */
    public UIFlow createUIFlow() {
        return new UIFlow();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link WritesUI }
     * 
     */
    public WritesUI createWritesUI() {
        return new WritesUI();
    }

    /**
     * Create an instance of {@link UIDisplay }
     * 
     */
    public UIDisplay createUIDisplay() {
        return new UIDisplay();
    }

    /**
     * Create an instance of {@link DisplaysImage }
     * 
     */
    public DisplaysImage createDisplaysImage() {
        return new DisplaysImage();
    }

    /**
     * Create an instance of {@link ManagesUI }
     * 
     */
    public ManagesUI createManagesUI() {
        return new ManagesUI();
    }

    /**
     * Create an instance of {@link Displays }
     * 
     */
    public Displays createDisplays() {
        return new Displays();
    }

    /**
     * Create an instance of {@link UIResource }
     * 
     */
    public UIResource createUIResource() {
        return new UIResource();
    }

    /**
     * Create an instance of {@link ReadsUI }
     * 
     */
    public ReadsUI createReadsUI() {
        return new ReadsUI();
    }

    /**
     * Create an instance of {@link UIField }
     * 
     */
    public UIField createUIField() {
        return new UIField();
    }

    /**
     * Create an instance of {@link UIRelationship }
     * 
     */
    public UIRelationship createUIRelationship() {
        return new UIRelationship();
    }

    /**
     * Create an instance of {@link UILayout }
     * 
     */
    public UILayout createUILayout() {
        return new UILayout();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIFlow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIFlow")
    public JAXBElement<UIFlow> createUIFlow(UIFlow value) {
        return new JAXBElement<UIFlow>(_UIFlow_QNAME, UIFlow.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WritesUI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "WritesUI")
    public JAXBElement<WritesUI> createWritesUI(WritesUI value) {
        return new JAXBElement<WritesUI>(_WritesUI_QNAME, WritesUI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadsUI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "ReadsUI")
    public JAXBElement<ReadsUI> createReadsUI(ReadsUI value) {
        return new JAXBElement<ReadsUI>(_ReadsUI_QNAME, ReadsUI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIRelationship")
    public JAXBElement<UIRelationship> createUIRelationship(UIRelationship value) {
        return new JAXBElement<UIRelationship>(_UIRelationship_QNAME, UIRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIResource")
    public JAXBElement<UIResource> createUIResource(UIResource value) {
        return new JAXBElement<UIResource>(_UIResource_QNAME, UIResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Screen }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "Screen")
    public JAXBElement<Screen> createScreen(Screen value) {
        return new JAXBElement<Screen>(_Screen_QNAME, Screen.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIDisplay }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIDisplay")
    public JAXBElement<UIDisplay> createUIDisplay(UIDisplay value) {
        return new JAXBElement<UIDisplay>(_UIDisplay_QNAME, UIDisplay.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractUIElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "AbstractUIElement")
    public JAXBElement<AbstractUIElement> createAbstractUIElement(AbstractUIElement value) {
        return new JAXBElement<AbstractUIElement>(_AbstractUIElement_QNAME, AbstractUIElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIModel")
    public JAXBElement<UIModel> createUIModel(UIModel value) {
        return new JAXBElement<UIModel>(_UIModel_QNAME, UIModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Report }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "Report")
    public JAXBElement<Report> createReport(Report value) {
        return new JAXBElement<Report>(_Report_QNAME, Report.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisplaysImage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "DisplaysImage")
    public JAXBElement<DisplaysImage> createDisplaysImage(DisplaysImage value) {
        return new JAXBElement<DisplaysImage>(_DisplaysImage_QNAME, DisplaysImage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIEvent")
    public JAXBElement<UIEvent> createUIEvent(UIEvent value) {
        return new JAXBElement<UIEvent>(_UIEvent_QNAME, UIEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIField")
    public JAXBElement<UIField> createUIField(UIField value) {
        return new JAXBElement<UIField>(_UIField_QNAME, UIField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UILayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UILayout")
    public JAXBElement<UILayout> createUILayout(UILayout value) {
        return new JAXBElement<UILayout>(_UILayout_QNAME, UILayout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIAction")
    public JAXBElement<UIAction> createUIAction(UIAction value) {
        return new JAXBElement<UIAction>(_UIAction_QNAME, UIAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractUIRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "AbstractUIRelationship")
    public JAXBElement<AbstractUIRelationship> createAbstractUIRelationship(AbstractUIRelationship value) {
        return new JAXBElement<AbstractUIRelationship>(_AbstractUIRelationship_QNAME, AbstractUIRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "UIElement")
    public JAXBElement<UIElement> createUIElement(UIElement value) {
        return new JAXBElement<UIElement>(_UIElement_QNAME, UIElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagesUI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "ManagesUI")
    public JAXBElement<ManagesUI> createManagesUI(ManagesUI value) {
        return new JAXBElement<ManagesUI>(_ManagesUI_QNAME, ManagesUI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Displays }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/ui", name = "Displays")
    public JAXBElement<Displays> createDisplays(Displays value) {
        return new JAXBElement<Displays>(_Displays_QNAME, Displays.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = UILayout.class)
    public JAXBElement<UIResource> createUILayoutTo(UIResource value) {
        return new JAXBElement<UIResource>(_UILayoutTo_QNAME, UIResource.class, UILayout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UIResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = UILayout.class)
    public JAXBElement<UIResource> createUILayoutFrom(UIResource value) {
        return new JAXBElement<UIResource>(_UILayoutFrom_QNAME, UIResource.class, UILayout.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractUIElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = UIFlow.class)
    public JAXBElement<AbstractUIElement> createUIFlowTo(AbstractUIElement value) {
        return new JAXBElement<AbstractUIElement>(_UILayoutTo_QNAME, AbstractUIElement.class, UIFlow.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractUIElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = UIFlow.class)
    public JAXBElement<AbstractUIElement> createUIFlowFrom(AbstractUIElement value) {
        return new JAXBElement<AbstractUIElement>(_UILayoutFrom_QNAME, AbstractUIElement.class, UIFlow.class, value);
    }

}
