//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.build.AbstractBuildElement;
import org.omg.schema.spec.kdm._1_1.code.AbstractCodeElement;
import org.omg.schema.spec.kdm._1_1.conceptual.AbstractConceptualElement;
import org.omg.schema.spec.kdm._1_1.data.AbstractDataElement;
import org.omg.schema.spec.kdm._1_1.event.AbstractEventElement;
import org.omg.schema.spec.kdm._1_1.platform.AbstractPlatformElement;
import org.omg.schema.spec.kdm._1_1.source.AbstractInventoryElement;
import org.omg.schema.spec.kdm._1_1.structure.AbstractStructureElement;
import org.omg.schema.spec.kdm._1_1.ui.AbstractUIElement;


/**
 * <p>Java class for KDMEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KDMEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}ModelElement">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KDMEntity")
@XmlSeeAlso({
    AbstractStructureElement.class,
    AbstractBuildElement.class,
    AbstractInventoryElement.class,
    AbstractPlatformElement.class,
    AbstractCodeElement.class,
    AbstractConceptualElement.class,
    AbstractUIElement.class,
    AbstractEventElement.class,
    AbstractDataElement.class
})
public abstract class KDMEntity
    extends ModelElement
{

    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
