//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.action.AbstractActionRelationship;
import org.omg.schema.spec.kdm._1_1.build.AbstractBuildRelationship;
import org.omg.schema.spec.kdm._1_1.code.AbstractCodeRelationship;
import org.omg.schema.spec.kdm._1_1.conceptual.AbstractConceptualRelationship;
import org.omg.schema.spec.kdm._1_1.data.AbstractDataRelationship;
import org.omg.schema.spec.kdm._1_1.event.AbstractEventRelationship;
import org.omg.schema.spec.kdm._1_1.platform.AbstractPlatformRelationship;
import org.omg.schema.spec.kdm._1_1.source.AbstractInventoryRelationship;
import org.omg.schema.spec.kdm._1_1.structure.AbstractStructureRelationship;
import org.omg.schema.spec.kdm._1_1.ui.AbstractUIRelationship;


/**
 * <p>Java class for KDMRelationship complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KDMRelationship">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}ModelElement">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KDMRelationship")
@XmlSeeAlso({
    AbstractStructureRelationship.class,
    AbstractBuildRelationship.class,
    AbstractInventoryRelationship.class,
    AbstractPlatformRelationship.class,
    AbstractCodeRelationship.class,
    AbstractConceptualRelationship.class,
    AbstractUIRelationship.class,
    AbstractEventRelationship.class,
    AbstractActionRelationship.class,
    AbstractDataRelationship.class
})
public abstract class KDMRelationship
    extends ModelElement
{


}
