//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.code.CommentUnit;
import org.omg.schema.spec.kdm._1_1.kdm.ExtendedValue;
import org.omg.schema.spec.kdm._1_1.kdm.KDMFramework;
import org.omg.schema.spec.kdm._1_1.kdm.Stereotype;


/**
 * <p>Java class for ModelElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}Element">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="stereotype" type="{http://schema.omg.org/spec/KDM/1.1/kdm}Stereotype"/>
 *         &lt;element name="taggedValue" type="{http://schema.omg.org/spec/KDM/1.1/kdm}ExtendedValue"/>
 *       &lt;/choice>
 *       &lt;attribute name="stereotype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelElement", propOrder = {
    "stereotypeOrTaggedValue"
})
@XmlSeeAlso({
    AggregatedRelationship.class,
    CommentUnit.class,
    KDMFramework.class,
    KDMRelationship.class,
    KDMEntity.class
})
public abstract class ModelElement
    extends Element
{

    @XmlElements({
        @XmlElement(name = "taggedValue", type = ExtendedValue.class),
        @XmlElement(name = "stereotype", type = Stereotype.class)
    })
    protected List<Element> stereotypeOrTaggedValue;
    @XmlAttribute
    protected String stereotype;

    /**
     * Gets the value of the stereotypeOrTaggedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stereotypeOrTaggedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStereotypeOrTaggedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedValue }
     * {@link Stereotype }
     * 
     * 
     */
    public List<Element> getStereotypeOrTaggedValue() {
        if (stereotypeOrTaggedValue == null) {
            stereotypeOrTaggedValue = new ArrayList<Element>();
        }
        return this.stereotypeOrTaggedValue;
    }

    /**
     * Gets the value of the stereotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStereotype() {
        return stereotype;
    }

    /**
     * Sets the value of the stereotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStereotype(String value) {
        this.stereotype = value;
    }

}
