//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.core;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KDMRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/core", "KDMRelationship");
    private final static QName _AggregatedRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/core", "AggregatedRelationship");
    private final static QName _ModelElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/core", "ModelElement");
    private final static QName _Element_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/core", "Element");
    private final static QName _KDMEntity_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/core", "KDMEntity");
    private final static QName _AggregatedRelationshipTo_QNAME = new QName("", "to");
    private final static QName _AggregatedRelationshipRelation_QNAME = new QName("", "relation");
    private final static QName _AggregatedRelationshipFrom_QNAME = new QName("", "from");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AggregatedRelationship }
     * 
     */
    public AggregatedRelationship createAggregatedRelationship() {
        return new AggregatedRelationship();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/core", name = "KDMRelationship")
    public JAXBElement<KDMRelationship> createKDMRelationship(KDMRelationship value) {
        return new JAXBElement<KDMRelationship>(_KDMRelationship_QNAME, KDMRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregatedRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/core", name = "AggregatedRelationship")
    public JAXBElement<AggregatedRelationship> createAggregatedRelationship(AggregatedRelationship value) {
        return new JAXBElement<AggregatedRelationship>(_AggregatedRelationship_QNAME, AggregatedRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/core", name = "ModelElement")
    public JAXBElement<ModelElement> createModelElement(ModelElement value) {
        return new JAXBElement<ModelElement>(_ModelElement_QNAME, ModelElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Element }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/core", name = "Element")
    public JAXBElement<Element> createElement(Element value) {
        return new JAXBElement<Element>(_Element_QNAME, Element.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/core", name = "KDMEntity")
    public JAXBElement<KDMEntity> createKDMEntity(KDMEntity value) {
        return new JAXBElement<KDMEntity>(_KDMEntity_QNAME, KDMEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = AggregatedRelationship.class)
    public JAXBElement<KDMEntity> createAggregatedRelationshipTo(KDMEntity value) {
        return new JAXBElement<KDMEntity>(_AggregatedRelationshipTo_QNAME, KDMEntity.class, AggregatedRelationship.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relation", scope = AggregatedRelationship.class)
    public JAXBElement<KDMRelationship> createAggregatedRelationshipRelation(KDMRelationship value) {
        return new JAXBElement<KDMRelationship>(_AggregatedRelationshipRelation_QNAME, KDMRelationship.class, AggregatedRelationship.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = AggregatedRelationship.class)
    public JAXBElement<KDMEntity> createAggregatedRelationshipFrom(KDMEntity value) {
        return new JAXBElement<KDMEntity>(_AggregatedRelationshipFrom_QNAME, KDMEntity.class, AggregatedRelationship.class, value);
    }

}
