//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.omg.org/spec/KDM/1.1/conceptual")
package org.omg.schema.spec.kdm._1_1.conceptual;
