//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.action;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.core.KDMRelationship;
import org.omg.schema.spec.kdm._1_1.data.HasContent;
import org.omg.schema.spec.kdm._1_1.data.ManagesData;
import org.omg.schema.spec.kdm._1_1.data.ProducesDataEvent;
import org.omg.schema.spec.kdm._1_1.data.ReadsColumnSet;
import org.omg.schema.spec.kdm._1_1.data.WritesColumnSet;
import org.omg.schema.spec.kdm._1_1.event.HasState;
import org.omg.schema.spec.kdm._1_1.event.ProducesEvent;
import org.omg.schema.spec.kdm._1_1.event.ReadsState;
import org.omg.schema.spec.kdm._1_1.platform.DefinedBy;
import org.omg.schema.spec.kdm._1_1.platform.ManagesResource;
import org.omg.schema.spec.kdm._1_1.platform.ReadsResource;
import org.omg.schema.spec.kdm._1_1.platform.WritesResource;
import org.omg.schema.spec.kdm._1_1.ui.ManagesUI;
import org.omg.schema.spec.kdm._1_1.ui.ReadsUI;
import org.omg.schema.spec.kdm._1_1.ui.WritesUI;


/**
 * <p>Java class for AbstractActionRelationship complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractActionRelationship">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}KDMRelationship">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractActionRelationship")
@XmlSeeAlso({
    WritesResource.class,
    DefinedBy.class,
    ManagesResource.class,
    ReadsResource.class,
    Addresses.class,
    ActionRelationship.class,
    UsesType.class,
    Creates.class,
    Throws.class,
    ExceptionFlow.class,
    Calls.class,
    ExitFlow.class,
    EntryFlow.class,
    Dispatches.class,
    Writes.class,
    ControlFlow.class,
    CompliesTo.class,
    Reads.class,
    ReadsUI.class,
    WritesUI.class,
    ManagesUI.class,
    ProducesEvent.class,
    HasState.class,
    ReadsState.class,
    ProducesDataEvent.class,
    ManagesData.class,
    ReadsColumnSet.class,
    HasContent.class,
    WritesColumnSet.class
})
public abstract class AbstractActionRelationship
    extends KDMRelationship
{


}
