//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.action;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.code.AbstractCodeElement;
import org.omg.schema.spec.kdm._1_1.core.ModelElement;


/**
 * <p>Java class for ActionElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/code}AbstractCodeElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="codeElement" type="{http://schema.omg.org/spec/KDM/1.1/code}AbstractCodeElement"/>
 *         &lt;element name="actionRelation" type="{http://schema.omg.org/spec/KDM/1.1/action}AbstractActionRelationship"/>
 *       &lt;/choice>
 *       &lt;attribute name="kind" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionElement", propOrder = {
    "codeElementOrActionRelation"
})
@XmlSeeAlso({
    BlockUnit.class
})
public class ActionElement
    extends AbstractCodeElement
{

    @XmlElements({
        @XmlElement(name = "codeElement", type = AbstractCodeElement.class),
        @XmlElement(name = "actionRelation", type = AbstractActionRelationship.class)
    })
    protected List<ModelElement> codeElementOrActionRelation;
    @XmlAttribute
    protected String kind;

    /**
     * Gets the value of the codeElementOrActionRelation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codeElementOrActionRelation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodeElementOrActionRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractCodeElement }
     * {@link AbstractActionRelationship }
     * 
     * 
     */
    public List<ModelElement> getCodeElementOrActionRelation() {
        if (codeElementOrActionRelation == null) {
            codeElementOrActionRelation = new ArrayList<ModelElement>();
        }
        return this.codeElementOrActionRelation;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKind(String value) {
        this.kind = value;
    }

}
