//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.code;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.action.ActionElement;
import org.omg.schema.spec.kdm._1_1.action.EntryFlow;
import org.omg.schema.spec.kdm._1_1.core.Element;
import org.omg.schema.spec.kdm._1_1.core.KDMEntity;
import org.omg.schema.spec.kdm._1_1.source.SourceRef;


/**
 * <p>Java class for AbstractCodeElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractCodeElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}KDMEntity">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="source" type="{http://schema.omg.org/spec/KDM/1.1/source}SourceRef"/>
 *         &lt;element name="comment" type="{http://schema.omg.org/spec/KDM/1.1/code}CommentUnit"/>
 *         &lt;element name="entryFlow" type="{http://schema.omg.org/spec/KDM/1.1/action}EntryFlow"/>
 *         &lt;element name="codeRelation" type="{http://schema.omg.org/spec/KDM/1.1/code}AbstractCodeRelationship"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractCodeElement", propOrder = {
    "sourceOrCommentOrEntryFlow"
})
@XmlSeeAlso({
    PreprocessorDirective.class,
    CodeItem.class,
    ActionElement.class
})
public abstract class AbstractCodeElement
    extends KDMEntity
{

    @XmlElements({
        @XmlElement(name = "source", type = SourceRef.class),
        @XmlElement(name = "comment", type = CommentUnit.class),
        @XmlElement(name = "entryFlow", type = EntryFlow.class),
        @XmlElement(name = "codeRelation", type = AbstractCodeRelationship.class)
    })
    protected List<Element> sourceOrCommentOrEntryFlow;

    /**
     * Gets the value of the sourceOrCommentOrEntryFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOrCommentOrEntryFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOrCommentOrEntryFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceRef }
     * {@link CommentUnit }
     * {@link EntryFlow }
     * {@link AbstractCodeRelationship }
     * 
     * 
     */
    public List<Element> getSourceOrCommentOrEntryFlow() {
        if (sourceOrCommentOrEntryFlow == null) {
            sourceOrCommentOrEntryFlow = new ArrayList<Element>();
        }
        return this.sourceOrCommentOrEntryFlow;
    }

}
