//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.code;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/code}ComputationalObject">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="type" type="{http://schema.omg.org/spec/KDM/1.1/code}Datatype"/>
 *         &lt;element name="codeElement" type="{http://schema.omg.org/spec/KDM/1.1/code}Datatype"/>
 *       &lt;/choice>
 *       &lt;attribute name="ext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataElement", propOrder = {
    "typeOrCodeElement"
})
@XmlSeeAlso({
    ParameterUnit.class,
    StorableUnit.class,
    IndexUnit.class,
    ItemUnit.class,
    MemberUnit.class,
    ValueElement.class
})
public class DataElement
    extends ComputationalObject
{

    @XmlElementRefs({
        @XmlElementRef(name = "codeElement", type = JAXBElement.class),
        @XmlElementRef(name = "type", type = JAXBElement.class)
    })
    protected List<JAXBElement<Datatype>> typeOrCodeElement;
    @XmlAttribute
    protected String ext;
    @XmlAttribute
    protected String size;
    @XmlAttribute(name = "type")
    protected String altType;

    /**
     * Gets the value of the typeOrCodeElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeOrCodeElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeOrCodeElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Datatype }{@code >}
     * {@link JAXBElement }{@code <}{@link Datatype }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Datatype>> getTypeOrCodeElement() {
        if (typeOrCodeElement == null) {
            typeOrCodeElement = new ArrayList<JAXBElement<Datatype>>();
        }
        return this.typeOrCodeElement;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExt(String value) {
        this.ext = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the altType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltType() {
        return altType;
    }

    /**
     * Sets the value of the altType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltType(String value) {
        this.altType = value;
    }

}
