//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.code;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MethodKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MethodKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="method"/>
 *     &lt;enumeration value="constructor"/>
 *     &lt;enumeration value="destructor"/>
 *     &lt;enumeration value="operator"/>
 *     &lt;enumeration value="virtual"/>
 *     &lt;enumeration value="abstract"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MethodKind")
@XmlEnum
public enum MethodKind {

    @XmlEnumValue("method")
    METHOD("method"),
    @XmlEnumValue("constructor")
    CONSTRUCTOR("constructor"),
    @XmlEnumValue("destructor")
    DESTRUCTOR("destructor"),
    @XmlEnumValue("operator")
    OPERATOR("operator"),
    @XmlEnumValue("virtual")
    VIRTUAL("virtual"),
    @XmlEnumValue("abstract")
    ABSTRACT("abstract"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    MethodKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MethodKind fromValue(String v) {
        for (MethodKind c: MethodKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
