//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.code;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.code package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OctetstringType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "OctetstringType");
    private final static QName _SequenceType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "SequenceType");
    private final static QName _NamespaceUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "NamespaceUnit");
    private final static QName _Implements_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Implements");
    private final static QName _Value_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Value");
    private final static QName _MacroDirective_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "MacroDirective");
    private final static QName _VisibleIn_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "VisibleIn");
    private final static QName _SharedUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "SharedUnit");
    private final static QName _ClassUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ClassUnit");
    private final static QName _DecimalType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "DecimalType");
    private final static QName _PointerType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "PointerType");
    private final static QName _TemplateType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "TemplateType");
    private final static QName _InstanceOf_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "InstanceOf");
    private final static QName _CodeAssembly_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CodeAssembly");
    private final static QName _Package_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Package");
    private final static QName _Imports_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Imports");
    private final static QName _HasValue_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "HasValue");
    private final static QName _MethodUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "MethodUnit");
    private final static QName _BitType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "BitType");
    private final static QName _Includes_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Includes");
    private final static QName _Signature_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Signature");
    private final static QName _DefinedType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "DefinedType");
    private final static QName _ItemUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ItemUnit");
    private final static QName _ConditionalDirective_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ConditionalDirective");
    private final static QName _DateType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "DateType");
    private final static QName _SetType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "SetType");
    private final static QName _CodeItem_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CodeItem");
    private final static QName _CallableUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CallableUnit");
    private final static QName _RecordType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "RecordType");
    private final static QName _SynonymType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "SynonymType");
    private final static QName _VariantTo_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "VariantTo");
    private final static QName _ImplementationOf_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ImplementationOf");
    private final static QName _Extends_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Extends");
    private final static QName _DerivedType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "DerivedType");
    private final static QName _CommentUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CommentUnit");
    private final static QName _InterfaceUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "InterfaceUnit");
    private final static QName _ParameterUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ParameterUnit");
    private final static QName _ParameterTo_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ParameterTo");
    private final static QName _CompositeType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CompositeType");
    private final static QName _AbstractCodeElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "AbstractCodeElement");
    private final static QName _ArrayType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ArrayType");
    private final static QName _PreprocessorDirective_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "PreprocessorDirective");
    private final static QName _IntegerType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "IntegerType");
    private final static QName _Redefines_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Redefines");
    private final static QName _HasType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "HasType");
    private final static QName _IndexUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "IndexUnit");
    private final static QName _CodeModel_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CodeModel");
    private final static QName _CharType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CharType");
    private final static QName _GeneratedFrom_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "GeneratedFrom");
    private final static QName _OrdinalType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "OrdinalType");
    private final static QName _IncludeDirective_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "IncludeDirective");
    private final static QName _StorableUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "StorableUnit");
    private final static QName _ChoiceType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ChoiceType");
    private final static QName _CodeElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CodeElement");
    private final static QName _ComputationalObject_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ComputationalObject");
    private final static QName _TimeType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "TimeType");
    private final static QName _MemberUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "MemberUnit");
    private final static QName _CodeRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CodeRelationship");
    private final static QName _DataElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "DataElement");
    private final static QName _TemplateUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "TemplateUnit");
    private final static QName _TypeUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "TypeUnit");
    private final static QName _CompilationUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "CompilationUnit");
    private final static QName _FloatType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "FloatType");
    private final static QName _MacroUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "MacroUnit");
    private final static QName _ValueList_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ValueList");
    private final static QName _BooleanType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "BooleanType");
    private final static QName _StringType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "StringType");
    private final static QName _ControlElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ControlElement");
    private final static QName _TemplateParameter_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "TemplateParameter");
    private final static QName _LanguageUnit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "LanguageUnit");
    private final static QName _OctetType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "OctetType");
    private final static QName _RangeType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "RangeType");
    private final static QName _Module_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Module");
    private final static QName _ValueElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ValueElement");
    private final static QName _VoidType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "VoidType");
    private final static QName _Datatype_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Datatype");
    private final static QName _AbstractCodeRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "AbstractCodeRelationship");
    private final static QName _EnumeratedType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "EnumeratedType");
    private final static QName _Expands_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "Expands");
    private final static QName _ScaledType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "ScaledType");
    private final static QName _BagType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "BagType");
    private final static QName _PrimitiveType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "PrimitiveType");
    private final static QName _BitstringType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/code", "BitstringType");
    private final static QName _VisibleInTo_QNAME = new QName("", "to");
    private final static QName _VisibleInFrom_QNAME = new QName("", "from");
    private final static QName _DataElementCodeElement_QNAME = new QName("", "codeElement");
    private final static QName _DataElementType_QNAME = new QName("", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.code
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link TemplateParameter }
     * 
     */
    public TemplateParameter createTemplateParameter() {
        return new TemplateParameter();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link BagType }
     * 
     */
    public BagType createBagType() {
        return new BagType();
    }

    /**
     * Create an instance of {@link OrdinalType }
     * 
     */
    public OrdinalType createOrdinalType() {
        return new OrdinalType();
    }

    /**
     * Create an instance of {@link StorableUnit }
     * 
     */
    public StorableUnit createStorableUnit() {
        return new StorableUnit();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link OctetType }
     * 
     */
    public OctetType createOctetType() {
        return new OctetType();
    }

    /**
     * Create an instance of {@link Includes }
     * 
     */
    public Includes createIncludes() {
        return new Includes();
    }

    /**
     * Create an instance of {@link IndexUnit }
     * 
     */
    public IndexUnit createIndexUnit() {
        return new IndexUnit();
    }

    /**
     * Create an instance of {@link DerivedType }
     * 
     */
    public DerivedType createDerivedType() {
        return new DerivedType();
    }

    /**
     * Create an instance of {@link PrimitiveType }
     * 
     */
    public PrimitiveType createPrimitiveType() {
        return new PrimitiveType();
    }

    /**
     * Create an instance of {@link StringType }
     * 
     */
    public StringType createStringType() {
        return new StringType();
    }

    /**
     * Create an instance of {@link BitstringType }
     * 
     */
    public BitstringType createBitstringType() {
        return new BitstringType();
    }

    /**
     * Create an instance of {@link ComputationalObject }
     * 
     */
    public ComputationalObject createComputationalObject() {
        return new ComputationalObject();
    }

    /**
     * Create an instance of {@link Extends }
     * 
     */
    public Extends createExtends() {
        return new Extends();
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link ImplementationOf }
     * 
     */
    public ImplementationOf createImplementationOf() {
        return new ImplementationOf();
    }

    /**
     * Create an instance of {@link GeneratedFrom }
     * 
     */
    public GeneratedFrom createGeneratedFrom() {
        return new GeneratedFrom();
    }

    /**
     * Create an instance of {@link VariantTo }
     * 
     */
    public VariantTo createVariantTo() {
        return new VariantTo();
    }

    /**
     * Create an instance of {@link BooleanType }
     * 
     */
    public BooleanType createBooleanType() {
        return new BooleanType();
    }

    /**
     * Create an instance of {@link HasValue }
     * 
     */
    public HasValue createHasValue() {
        return new HasValue();
    }

    /**
     * Create an instance of {@link HasType }
     * 
     */
    public HasType createHasType() {
        return new HasType();
    }

    /**
     * Create an instance of {@link CodeRelationship }
     * 
     */
    public CodeRelationship createCodeRelationship() {
        return new CodeRelationship();
    }

    /**
     * Create an instance of {@link CodeModel }
     * 
     */
    public CodeModel createCodeModel() {
        return new CodeModel();
    }

    /**
     * Create an instance of {@link Datatype }
     * 
     */
    public Datatype createDatatype() {
        return new Datatype();
    }

    /**
     * Create an instance of {@link Imports }
     * 
     */
    public Imports createImports() {
        return new Imports();
    }

    /**
     * Create an instance of {@link Redefines }
     * 
     */
    public Redefines createRedefines() {
        return new Redefines();
    }

    /**
     * Create an instance of {@link NamespaceUnit }
     * 
     */
    public NamespaceUnit createNamespaceUnit() {
        return new NamespaceUnit();
    }

    /**
     * Create an instance of {@link CharType }
     * 
     */
    public CharType createCharType() {
        return new CharType();
    }

    /**
     * Create an instance of {@link DataElement }
     * 
     */
    public DataElement createDataElement() {
        return new DataElement();
    }

    /**
     * Create an instance of {@link InterfaceUnit }
     * 
     */
    public InterfaceUnit createInterfaceUnit() {
        return new InterfaceUnit();
    }

    /**
     * Create an instance of {@link MacroUnit }
     * 
     */
    public MacroUnit createMacroUnit() {
        return new MacroUnit();
    }

    /**
     * Create an instance of {@link CodeElement }
     * 
     */
    public CodeElement createCodeElement() {
        return new CodeElement();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link InstanceOf }
     * 
     */
    public InstanceOf createInstanceOf() {
        return new InstanceOf();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link ClassUnit }
     * 
     */
    public ClassUnit createClassUnit() {
        return new ClassUnit();
    }

    /**
     * Create an instance of {@link ParameterTo }
     * 
     */
    public ParameterTo createParameterTo() {
        return new ParameterTo();
    }

    /**
     * Create an instance of {@link PointerType }
     * 
     */
    public PointerType createPointerType() {
        return new PointerType();
    }

    /**
     * Create an instance of {@link Implements }
     * 
     */
    public Implements createImplements() {
        return new Implements();
    }

    /**
     * Create an instance of {@link EnumeratedType }
     * 
     */
    public EnumeratedType createEnumeratedType() {
        return new EnumeratedType();
    }

    /**
     * Create an instance of {@link TypeUnit }
     * 
     */
    public TypeUnit createTypeUnit() {
        return new TypeUnit();
    }

    /**
     * Create an instance of {@link ConditionalDirective }
     * 
     */
    public ConditionalDirective createConditionalDirective() {
        return new ConditionalDirective();
    }

    /**
     * Create an instance of {@link CallableUnit }
     * 
     */
    public CallableUnit createCallableUnit() {
        return new CallableUnit();
    }

    /**
     * Create an instance of {@link OctetstringType }
     * 
     */
    public OctetstringType createOctetstringType() {
        return new OctetstringType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link ValueElement }
     * 
     */
    public ValueElement createValueElement() {
        return new ValueElement();
    }

    /**
     * Create an instance of {@link FloatType }
     * 
     */
    public FloatType createFloatType() {
        return new FloatType();
    }

    /**
     * Create an instance of {@link VisibleIn }
     * 
     */
    public VisibleIn createVisibleIn() {
        return new VisibleIn();
    }

    /**
     * Create an instance of {@link VoidType }
     * 
     */
    public VoidType createVoidType() {
        return new VoidType();
    }

    /**
     * Create an instance of {@link CommentUnit }
     * 
     */
    public CommentUnit createCommentUnit() {
        return new CommentUnit();
    }

    /**
     * Create an instance of {@link DecimalType }
     * 
     */
    public DecimalType createDecimalType() {
        return new DecimalType();
    }

    /**
     * Create an instance of {@link MethodUnit }
     * 
     */
    public MethodUnit createMethodUnit() {
        return new MethodUnit();
    }

    /**
     * Create an instance of {@link ControlElement }
     * 
     */
    public ControlElement createControlElement() {
        return new ControlElement();
    }

    /**
     * Create an instance of {@link IncludeDirective }
     * 
     */
    public IncludeDirective createIncludeDirective() {
        return new IncludeDirective();
    }

    /**
     * Create an instance of {@link PreprocessorDirective }
     * 
     */
    public PreprocessorDirective createPreprocessorDirective() {
        return new PreprocessorDirective();
    }

    /**
     * Create an instance of {@link CompilationUnit }
     * 
     */
    public CompilationUnit createCompilationUnit() {
        return new CompilationUnit();
    }

    /**
     * Create an instance of {@link ItemUnit }
     * 
     */
    public ItemUnit createItemUnit() {
        return new ItemUnit();
    }

    /**
     * Create an instance of {@link ParameterUnit }
     * 
     */
    public ParameterUnit createParameterUnit() {
        return new ParameterUnit();
    }

    /**
     * Create an instance of {@link CodeAssembly }
     * 
     */
    public CodeAssembly createCodeAssembly() {
        return new CodeAssembly();
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link TemplateUnit }
     * 
     */
    public TemplateUnit createTemplateUnit() {
        return new TemplateUnit();
    }

    /**
     * Create an instance of {@link IntegerType }
     * 
     */
    public IntegerType createIntegerType() {
        return new IntegerType();
    }

    /**
     * Create an instance of {@link SharedUnit }
     * 
     */
    public SharedUnit createSharedUnit() {
        return new SharedUnit();
    }

    /**
     * Create an instance of {@link BitType }
     * 
     */
    public BitType createBitType() {
        return new BitType();
    }

    /**
     * Create an instance of {@link ChoiceType }
     * 
     */
    public ChoiceType createChoiceType() {
        return new ChoiceType();
    }

    /**
     * Create an instance of {@link LanguageUnit }
     * 
     */
    public LanguageUnit createLanguageUnit() {
        return new LanguageUnit();
    }

    /**
     * Create an instance of {@link Expands }
     * 
     */
    public Expands createExpands() {
        return new Expands();
    }

    /**
     * Create an instance of {@link CompositeType }
     * 
     */
    public CompositeType createCompositeType() {
        return new CompositeType();
    }

    /**
     * Create an instance of {@link ValueList }
     * 
     */
    public ValueList createValueList() {
        return new ValueList();
    }

    /**
     * Create an instance of {@link MemberUnit }
     * 
     */
    public MemberUnit createMemberUnit() {
        return new MemberUnit();
    }

    /**
     * Create an instance of {@link ScaledType }
     * 
     */
    public ScaledType createScaledType() {
        return new ScaledType();
    }

    /**
     * Create an instance of {@link SetType }
     * 
     */
    public SetType createSetType() {
        return new SetType();
    }

    /**
     * Create an instance of {@link SynonymType }
     * 
     */
    public SynonymType createSynonymType() {
        return new SynonymType();
    }

    /**
     * Create an instance of {@link ArrayType }
     * 
     */
    public ArrayType createArrayType() {
        return new ArrayType();
    }

    /**
     * Create an instance of {@link MacroDirective }
     * 
     */
    public MacroDirective createMacroDirective() {
        return new MacroDirective();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OctetstringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "OctetstringType")
    public JAXBElement<OctetstringType> createOctetstringType(OctetstringType value) {
        return new JAXBElement<OctetstringType>(_OctetstringType_QNAME, OctetstringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "SequenceType")
    public JAXBElement<SequenceType> createSequenceType(SequenceType value) {
        return new JAXBElement<SequenceType>(_SequenceType_QNAME, SequenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamespaceUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "NamespaceUnit")
    public JAXBElement<NamespaceUnit> createNamespaceUnit(NamespaceUnit value) {
        return new JAXBElement<NamespaceUnit>(_NamespaceUnit_QNAME, NamespaceUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Implements }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Implements")
    public JAXBElement<Implements> createImplements(Implements value) {
        return new JAXBElement<Implements>(_Implements_QNAME, Implements.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Value")
    public JAXBElement<Value> createValue(Value value) {
        return new JAXBElement<Value>(_Value_QNAME, Value.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MacroDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "MacroDirective")
    public JAXBElement<MacroDirective> createMacroDirective(MacroDirective value) {
        return new JAXBElement<MacroDirective>(_MacroDirective_QNAME, MacroDirective.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VisibleIn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "VisibleIn")
    public JAXBElement<VisibleIn> createVisibleIn(VisibleIn value) {
        return new JAXBElement<VisibleIn>(_VisibleIn_QNAME, VisibleIn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "SharedUnit")
    public JAXBElement<SharedUnit> createSharedUnit(SharedUnit value) {
        return new JAXBElement<SharedUnit>(_SharedUnit_QNAME, SharedUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ClassUnit")
    public JAXBElement<ClassUnit> createClassUnit(ClassUnit value) {
        return new JAXBElement<ClassUnit>(_ClassUnit_QNAME, ClassUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecimalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "DecimalType")
    public JAXBElement<DecimalType> createDecimalType(DecimalType value) {
        return new JAXBElement<DecimalType>(_DecimalType_QNAME, DecimalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "PointerType")
    public JAXBElement<PointerType> createPointerType(PointerType value) {
        return new JAXBElement<PointerType>(_PointerType_QNAME, PointerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "TemplateType")
    public JAXBElement<TemplateType> createTemplateType(TemplateType value) {
        return new JAXBElement<TemplateType>(_TemplateType_QNAME, TemplateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstanceOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "InstanceOf")
    public JAXBElement<InstanceOf> createInstanceOf(InstanceOf value) {
        return new JAXBElement<InstanceOf>(_InstanceOf_QNAME, InstanceOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeAssembly }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CodeAssembly")
    public JAXBElement<CodeAssembly> createCodeAssembly(CodeAssembly value) {
        return new JAXBElement<CodeAssembly>(_CodeAssembly_QNAME, CodeAssembly.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Package }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Package")
    public JAXBElement<Package> createPackage(Package value) {
        return new JAXBElement<Package>(_Package_QNAME, Package.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Imports }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Imports")
    public JAXBElement<Imports> createImports(Imports value) {
        return new JAXBElement<Imports>(_Imports_QNAME, Imports.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "HasValue")
    public JAXBElement<HasValue> createHasValue(HasValue value) {
        return new JAXBElement<HasValue>(_HasValue_QNAME, HasValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MethodUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "MethodUnit")
    public JAXBElement<MethodUnit> createMethodUnit(MethodUnit value) {
        return new JAXBElement<MethodUnit>(_MethodUnit_QNAME, MethodUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "BitType")
    public JAXBElement<BitType> createBitType(BitType value) {
        return new JAXBElement<BitType>(_BitType_QNAME, BitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Includes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Includes")
    public JAXBElement<Includes> createIncludes(Includes value) {
        return new JAXBElement<Includes>(_Includes_QNAME, Includes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Signature }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Signature")
    public JAXBElement<Signature> createSignature(Signature value) {
        return new JAXBElement<Signature>(_Signature_QNAME, Signature.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "DefinedType")
    public JAXBElement<DefinedType> createDefinedType(DefinedType value) {
        return new JAXBElement<DefinedType>(_DefinedType_QNAME, DefinedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ItemUnit")
    public JAXBElement<ItemUnit> createItemUnit(ItemUnit value) {
        return new JAXBElement<ItemUnit>(_ItemUnit_QNAME, ItemUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionalDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ConditionalDirective")
    public JAXBElement<ConditionalDirective> createConditionalDirective(ConditionalDirective value) {
        return new JAXBElement<ConditionalDirective>(_ConditionalDirective_QNAME, ConditionalDirective.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "DateType")
    public JAXBElement<DateType> createDateType(DateType value) {
        return new JAXBElement<DateType>(_DateType_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "SetType")
    public JAXBElement<SetType> createSetType(SetType value) {
        return new JAXBElement<SetType>(_SetType_QNAME, SetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CodeItem")
    public JAXBElement<CodeItem> createCodeItem(CodeItem value) {
        return new JAXBElement<CodeItem>(_CodeItem_QNAME, CodeItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallableUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CallableUnit")
    public JAXBElement<CallableUnit> createCallableUnit(CallableUnit value) {
        return new JAXBElement<CallableUnit>(_CallableUnit_QNAME, CallableUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "RecordType")
    public JAXBElement<RecordType> createRecordType(RecordType value) {
        return new JAXBElement<RecordType>(_RecordType_QNAME, RecordType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SynonymType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "SynonymType")
    public JAXBElement<SynonymType> createSynonymType(SynonymType value) {
        return new JAXBElement<SynonymType>(_SynonymType_QNAME, SynonymType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariantTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "VariantTo")
    public JAXBElement<VariantTo> createVariantTo(VariantTo value) {
        return new JAXBElement<VariantTo>(_VariantTo_QNAME, VariantTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImplementationOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ImplementationOf")
    public JAXBElement<ImplementationOf> createImplementationOf(ImplementationOf value) {
        return new JAXBElement<ImplementationOf>(_ImplementationOf_QNAME, ImplementationOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Extends }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Extends")
    public JAXBElement<Extends> createExtends(Extends value) {
        return new JAXBElement<Extends>(_Extends_QNAME, Extends.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "DerivedType")
    public JAXBElement<DerivedType> createDerivedType(DerivedType value) {
        return new JAXBElement<DerivedType>(_DerivedType_QNAME, DerivedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CommentUnit")
    public JAXBElement<CommentUnit> createCommentUnit(CommentUnit value) {
        return new JAXBElement<CommentUnit>(_CommentUnit_QNAME, CommentUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "InterfaceUnit")
    public JAXBElement<InterfaceUnit> createInterfaceUnit(InterfaceUnit value) {
        return new JAXBElement<InterfaceUnit>(_InterfaceUnit_QNAME, InterfaceUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ParameterUnit")
    public JAXBElement<ParameterUnit> createParameterUnit(ParameterUnit value) {
        return new JAXBElement<ParameterUnit>(_ParameterUnit_QNAME, ParameterUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ParameterTo")
    public JAXBElement<ParameterTo> createParameterTo(ParameterTo value) {
        return new JAXBElement<ParameterTo>(_ParameterTo_QNAME, ParameterTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompositeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CompositeType")
    public JAXBElement<CompositeType> createCompositeType(CompositeType value) {
        return new JAXBElement<CompositeType>(_CompositeType_QNAME, CompositeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCodeElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "AbstractCodeElement")
    public JAXBElement<AbstractCodeElement> createAbstractCodeElement(AbstractCodeElement value) {
        return new JAXBElement<AbstractCodeElement>(_AbstractCodeElement_QNAME, AbstractCodeElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ArrayType")
    public JAXBElement<ArrayType> createArrayType(ArrayType value) {
        return new JAXBElement<ArrayType>(_ArrayType_QNAME, ArrayType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "PreprocessorDirective")
    public JAXBElement<PreprocessorDirective> createPreprocessorDirective(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_PreprocessorDirective_QNAME, PreprocessorDirective.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "IntegerType")
    public JAXBElement<IntegerType> createIntegerType(IntegerType value) {
        return new JAXBElement<IntegerType>(_IntegerType_QNAME, IntegerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Redefines }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Redefines")
    public JAXBElement<Redefines> createRedefines(Redefines value) {
        return new JAXBElement<Redefines>(_Redefines_QNAME, Redefines.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "HasType")
    public JAXBElement<HasType> createHasType(HasType value) {
        return new JAXBElement<HasType>(_HasType_QNAME, HasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "IndexUnit")
    public JAXBElement<IndexUnit> createIndexUnit(IndexUnit value) {
        return new JAXBElement<IndexUnit>(_IndexUnit_QNAME, IndexUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CodeModel")
    public JAXBElement<CodeModel> createCodeModel(CodeModel value) {
        return new JAXBElement<CodeModel>(_CodeModel_QNAME, CodeModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CharType")
    public JAXBElement<CharType> createCharType(CharType value) {
        return new JAXBElement<CharType>(_CharType_QNAME, CharType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratedFrom }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "GeneratedFrom")
    public JAXBElement<GeneratedFrom> createGeneratedFrom(GeneratedFrom value) {
        return new JAXBElement<GeneratedFrom>(_GeneratedFrom_QNAME, GeneratedFrom.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrdinalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "OrdinalType")
    public JAXBElement<OrdinalType> createOrdinalType(OrdinalType value) {
        return new JAXBElement<OrdinalType>(_OrdinalType_QNAME, OrdinalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncludeDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "IncludeDirective")
    public JAXBElement<IncludeDirective> createIncludeDirective(IncludeDirective value) {
        return new JAXBElement<IncludeDirective>(_IncludeDirective_QNAME, IncludeDirective.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StorableUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "StorableUnit")
    public JAXBElement<StorableUnit> createStorableUnit(StorableUnit value) {
        return new JAXBElement<StorableUnit>(_StorableUnit_QNAME, StorableUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ChoiceType")
    public JAXBElement<ChoiceType> createChoiceType(ChoiceType value) {
        return new JAXBElement<ChoiceType>(_ChoiceType_QNAME, ChoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CodeElement")
    public JAXBElement<CodeElement> createCodeElement(CodeElement value) {
        return new JAXBElement<CodeElement>(_CodeElement_QNAME, CodeElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComputationalObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ComputationalObject")
    public JAXBElement<ComputationalObject> createComputationalObject(ComputationalObject value) {
        return new JAXBElement<ComputationalObject>(_ComputationalObject_QNAME, ComputationalObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "TimeType")
    public JAXBElement<TimeType> createTimeType(TimeType value) {
        return new JAXBElement<TimeType>(_TimeType_QNAME, TimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MemberUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "MemberUnit")
    public JAXBElement<MemberUnit> createMemberUnit(MemberUnit value) {
        return new JAXBElement<MemberUnit>(_MemberUnit_QNAME, MemberUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CodeRelationship")
    public JAXBElement<CodeRelationship> createCodeRelationship(CodeRelationship value) {
        return new JAXBElement<CodeRelationship>(_CodeRelationship_QNAME, CodeRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "DataElement")
    public JAXBElement<DataElement> createDataElement(DataElement value) {
        return new JAXBElement<DataElement>(_DataElement_QNAME, DataElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "TemplateUnit")
    public JAXBElement<TemplateUnit> createTemplateUnit(TemplateUnit value) {
        return new JAXBElement<TemplateUnit>(_TemplateUnit_QNAME, TemplateUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "TypeUnit")
    public JAXBElement<TypeUnit> createTypeUnit(TypeUnit value) {
        return new JAXBElement<TypeUnit>(_TypeUnit_QNAME, TypeUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompilationUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "CompilationUnit")
    public JAXBElement<CompilationUnit> createCompilationUnit(CompilationUnit value) {
        return new JAXBElement<CompilationUnit>(_CompilationUnit_QNAME, CompilationUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FloatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "FloatType")
    public JAXBElement<FloatType> createFloatType(FloatType value) {
        return new JAXBElement<FloatType>(_FloatType_QNAME, FloatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MacroUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "MacroUnit")
    public JAXBElement<MacroUnit> createMacroUnit(MacroUnit value) {
        return new JAXBElement<MacroUnit>(_MacroUnit_QNAME, MacroUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ValueList")
    public JAXBElement<ValueList> createValueList(ValueList value) {
        return new JAXBElement<ValueList>(_ValueList_QNAME, ValueList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "BooleanType")
    public JAXBElement<BooleanType> createBooleanType(BooleanType value) {
        return new JAXBElement<BooleanType>(_BooleanType_QNAME, BooleanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "StringType")
    public JAXBElement<StringType> createStringType(StringType value) {
        return new JAXBElement<StringType>(_StringType_QNAME, StringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ControlElement")
    public JAXBElement<ControlElement> createControlElement(ControlElement value) {
        return new JAXBElement<ControlElement>(_ControlElement_QNAME, ControlElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "TemplateParameter")
    public JAXBElement<TemplateParameter> createTemplateParameter(TemplateParameter value) {
        return new JAXBElement<TemplateParameter>(_TemplateParameter_QNAME, TemplateParameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "LanguageUnit")
    public JAXBElement<LanguageUnit> createLanguageUnit(LanguageUnit value) {
        return new JAXBElement<LanguageUnit>(_LanguageUnit_QNAME, LanguageUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OctetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "OctetType")
    public JAXBElement<OctetType> createOctetType(OctetType value) {
        return new JAXBElement<OctetType>(_OctetType_QNAME, OctetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "RangeType")
    public JAXBElement<RangeType> createRangeType(RangeType value) {
        return new JAXBElement<RangeType>(_RangeType_QNAME, RangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Module }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Module")
    public JAXBElement<Module> createModule(Module value) {
        return new JAXBElement<Module>(_Module_QNAME, Module.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ValueElement")
    public JAXBElement<ValueElement> createValueElement(ValueElement value) {
        return new JAXBElement<ValueElement>(_ValueElement_QNAME, ValueElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoidType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "VoidType")
    public JAXBElement<VoidType> createVoidType(VoidType value) {
        return new JAXBElement<VoidType>(_VoidType_QNAME, VoidType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Datatype")
    public JAXBElement<Datatype> createDatatype(Datatype value) {
        return new JAXBElement<Datatype>(_Datatype_QNAME, Datatype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCodeRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "AbstractCodeRelationship")
    public JAXBElement<AbstractCodeRelationship> createAbstractCodeRelationship(AbstractCodeRelationship value) {
        return new JAXBElement<AbstractCodeRelationship>(_AbstractCodeRelationship_QNAME, AbstractCodeRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumeratedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "EnumeratedType")
    public JAXBElement<EnumeratedType> createEnumeratedType(EnumeratedType value) {
        return new JAXBElement<EnumeratedType>(_EnumeratedType_QNAME, EnumeratedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expands }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "Expands")
    public JAXBElement<Expands> createExpands(Expands value) {
        return new JAXBElement<Expands>(_Expands_QNAME, Expands.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaledType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "ScaledType")
    public JAXBElement<ScaledType> createScaledType(ScaledType value) {
        return new JAXBElement<ScaledType>(_ScaledType_QNAME, ScaledType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "BagType")
    public JAXBElement<BagType> createBagType(BagType value) {
        return new JAXBElement<BagType>(_BagType_QNAME, BagType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimitiveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "PrimitiveType")
    public JAXBElement<PrimitiveType> createPrimitiveType(PrimitiveType value) {
        return new JAXBElement<PrimitiveType>(_PrimitiveType_QNAME, PrimitiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BitstringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/code", name = "BitstringType")
    public JAXBElement<BitstringType> createBitstringType(BitstringType value) {
        return new JAXBElement<BitstringType>(_BitstringType_QNAME, BitstringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = VisibleIn.class)
    public JAXBElement<CodeItem> createVisibleInTo(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInTo_QNAME, CodeItem.class, VisibleIn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = VisibleIn.class)
    public JAXBElement<CodeItem> createVisibleInFrom(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInFrom_QNAME, CodeItem.class, VisibleIn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = ImplementationOf.class)
    public JAXBElement<CodeItem> createImplementationOfTo(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInTo_QNAME, CodeItem.class, ImplementationOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = ImplementationOf.class)
    public JAXBElement<CodeItem> createImplementationOfFrom(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInFrom_QNAME, CodeItem.class, ImplementationOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = VariantTo.class)
    public JAXBElement<PreprocessorDirective> createVariantToTo(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInTo_QNAME, PreprocessorDirective.class, VariantTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = VariantTo.class)
    public JAXBElement<PreprocessorDirective> createVariantToFrom(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInFrom_QNAME, PreprocessorDirective.class, VariantTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Redefines.class)
    public JAXBElement<PreprocessorDirective> createRedefinesTo(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInTo_QNAME, PreprocessorDirective.class, Redefines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Redefines.class)
    public JAXBElement<PreprocessorDirective> createRedefinesFrom(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInFrom_QNAME, PreprocessorDirective.class, Redefines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codeElement", scope = DataElement.class)
    public JAXBElement<Datatype> createDataElementCodeElement(Datatype value) {
        return new JAXBElement<Datatype>(_DataElementCodeElement_QNAME, Datatype.class, DataElement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = DataElement.class)
    public JAXBElement<Datatype> createDataElementType(Datatype value) {
        return new JAXBElement<Datatype>(_DataElementType_QNAME, Datatype.class, DataElement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Implements.class)
    public JAXBElement<CodeItem> createImplementsTo(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInTo_QNAME, CodeItem.class, Implements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Implements.class)
    public JAXBElement<CodeItem> createImplementsFrom(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInFrom_QNAME, CodeItem.class, Implements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Expands.class)
    public JAXBElement<PreprocessorDirective> createExpandsTo(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInTo_QNAME, PreprocessorDirective.class, Expands.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreprocessorDirective }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Expands.class)
    public JAXBElement<PreprocessorDirective> createExpandsFrom(PreprocessorDirective value) {
        return new JAXBElement<PreprocessorDirective>(_VisibleInFrom_QNAME, PreprocessorDirective.class, Expands.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Imports.class)
    public JAXBElement<CodeItem> createImportsTo(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInTo_QNAME, CodeItem.class, Imports.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Imports.class)
    public JAXBElement<CodeItem> createImportsFrom(CodeItem value) {
        return new JAXBElement<CodeItem>(_VisibleInFrom_QNAME, CodeItem.class, Imports.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codeElement", scope = DefinedType.class)
    public JAXBElement<Datatype> createDefinedTypeCodeElement(Datatype value) {
        return new JAXBElement<Datatype>(_DataElementCodeElement_QNAME, Datatype.class, DefinedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = DefinedType.class)
    public JAXBElement<Datatype> createDefinedTypeType(Datatype value) {
        return new JAXBElement<Datatype>(_DataElementType_QNAME, Datatype.class, DefinedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = Extends.class)
    public JAXBElement<Datatype> createExtendsTo(Datatype value) {
        return new JAXBElement<Datatype>(_VisibleInTo_QNAME, Datatype.class, Extends.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datatype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = Extends.class)
    public JAXBElement<Datatype> createExtendsFrom(Datatype value) {
        return new JAXBElement<Datatype>(_VisibleInFrom_QNAME, Datatype.class, Extends.class, value);
    }

}
