//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.code;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Signature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Signature">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/code}Datatype">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="parameterUnit" type="{http://schema.omg.org/spec/KDM/1.1/code}ParameterUnit"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Signature", propOrder = {
    "parameterUnit"
})
public class Signature
    extends Datatype
{

    protected List<ParameterUnit> parameterUnit;

    /**
     * Gets the value of the parameterUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterUnit }
     * 
     * 
     */
    public List<ParameterUnit> getParameterUnit() {
        if (parameterUnit == null) {
            parameterUnit = new ArrayList<ParameterUnit>();
        }
        return this.parameterUnit;
    }

}
