//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.kdm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.core.Element;
import org.omg.schema.spec.kdm._1_1.core.ModelElement;


/**
 * <p>Java class for KDMFramework complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KDMFramework">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}ModelElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="audit" type="{http://schema.omg.org/spec/KDM/1.1/kdm}Audit"/>
 *         &lt;element name="extensionFamily" type="{http://schema.omg.org/spec/KDM/1.1/kdm}ExtensionFamily"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KDMFramework", propOrder = {
    "auditOrExtensionFamily"
})
@XmlSeeAlso({
    Segment.class,
    KDMModel.class
})
public abstract class KDMFramework
    extends ModelElement
{

    @XmlElements({
        @XmlElement(name = "audit", type = Audit.class),
        @XmlElement(name = "extensionFamily", type = ExtensionFamily.class)
    })
    protected List<Element> auditOrExtensionFamily;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the auditOrExtensionFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auditOrExtensionFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuditOrExtensionFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Audit }
     * {@link ExtensionFamily }
     * 
     * 
     */
    public List<Element> getAuditOrExtensionFamily() {
        if (auditOrExtensionFamily == null) {
            auditOrExtensionFamily = new ArrayList<Element>();
        }
        return this.auditOrExtensionFamily;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
