//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.kdm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.kdm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Annotation_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "Annotation");
    private final static QName _Attribute_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "Attribute");
    private final static QName _TaggedValue_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "TaggedValue");
    private final static QName _KDMModel_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "KDMModel");
    private final static QName _TagDefinition_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "TagDefinition");
    private final static QName _Segment_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "Segment");
    private final static QName _Stereotype_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "Stereotype");
    private final static QName _Audit_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "Audit");
    private final static QName _KDMFramework_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "KDMFramework");
    private final static QName _TaggedRef_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "TaggedRef");
    private final static QName _ExtensionFamily_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "ExtensionFamily");
    private final static QName _ExtendedValue_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/kdm", "ExtendedValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.kdm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Stereotype }
     * 
     */
    public Stereotype createStereotype() {
        return new Stereotype();
    }

    /**
     * Create an instance of {@link TaggedRef }
     * 
     */
    public TaggedRef createTaggedRef() {
        return new TaggedRef();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link TagDefinition }
     * 
     */
    public TagDefinition createTagDefinition() {
        return new TagDefinition();
    }

    /**
     * Create an instance of {@link ExtensionFamily }
     * 
     */
    public ExtensionFamily createExtensionFamily() {
        return new ExtensionFamily();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Audit }
     * 
     */
    public Audit createAudit() {
        return new Audit();
    }

    /**
     * Create an instance of {@link TaggedValue }
     * 
     */
    public TaggedValue createTaggedValue() {
        return new TaggedValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Annotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "Annotation")
    public JAXBElement<Annotation> createAnnotation(Annotation value) {
        return new JAXBElement<Annotation>(_Annotation_QNAME, Annotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Attribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "Attribute")
    public JAXBElement<Attribute> createAttribute(Attribute value) {
        return new JAXBElement<Attribute>(_Attribute_QNAME, Attribute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaggedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "TaggedValue")
    public JAXBElement<TaggedValue> createTaggedValue(TaggedValue value) {
        return new JAXBElement<TaggedValue>(_TaggedValue_QNAME, TaggedValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "KDMModel")
    public JAXBElement<KDMModel> createKDMModel(KDMModel value) {
        return new JAXBElement<KDMModel>(_KDMModel_QNAME, KDMModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TagDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "TagDefinition")
    public JAXBElement<TagDefinition> createTagDefinition(TagDefinition value) {
        return new JAXBElement<TagDefinition>(_TagDefinition_QNAME, TagDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Segment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "Segment")
    public JAXBElement<Segment> createSegment(Segment value) {
        return new JAXBElement<Segment>(_Segment_QNAME, Segment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stereotype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "Stereotype")
    public JAXBElement<Stereotype> createStereotype(Stereotype value) {
        return new JAXBElement<Stereotype>(_Stereotype_QNAME, Stereotype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Audit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "Audit")
    public JAXBElement<Audit> createAudit(Audit value) {
        return new JAXBElement<Audit>(_Audit_QNAME, Audit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KDMFramework }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "KDMFramework")
    public JAXBElement<KDMFramework> createKDMFramework(KDMFramework value) {
        return new JAXBElement<KDMFramework>(_KDMFramework_QNAME, KDMFramework.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaggedRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "TaggedRef")
    public JAXBElement<TaggedRef> createTaggedRef(TaggedRef value) {
        return new JAXBElement<TaggedRef>(_TaggedRef_QNAME, TaggedRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionFamily }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "ExtensionFamily")
    public JAXBElement<ExtensionFamily> createExtensionFamily(ExtensionFamily value) {
        return new JAXBElement<ExtensionFamily>(_ExtensionFamily_QNAME, ExtensionFamily.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/kdm", name = "ExtendedValue")
    public JAXBElement<ExtendedValue> createExtendedValue(ExtendedValue value) {
        return new JAXBElement<ExtendedValue>(_ExtendedValue_QNAME, ExtendedValue.class, null, value);
    }

}
