//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.platform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Machine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Machine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/platform}AbstractPlatformElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="deployedComponent" type="{http://schema.omg.org/spec/KDM/1.1/platform}DeployedComponent"/>
 *         &lt;element name="deployedResource" type="{http://schema.omg.org/spec/KDM/1.1/platform}DeployedResource"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Machine", propOrder = {
    "deployedComponentOrDeployedResource"
})
public class Machine
    extends AbstractPlatformElement
{

    @XmlElements({
        @XmlElement(name = "deployedComponent", type = DeployedComponent.class),
        @XmlElement(name = "deployedResource", type = DeployedResource.class)
    })
    protected List<AbstractPlatformElement> deployedComponentOrDeployedResource;

    /**
     * Gets the value of the deployedComponentOrDeployedResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deployedComponentOrDeployedResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeployedComponentOrDeployedResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeployedComponent }
     * {@link DeployedResource }
     * 
     * 
     */
    public List<AbstractPlatformElement> getDeployedComponentOrDeployedResource() {
        if (deployedComponentOrDeployedResource == null) {
            deployedComponentOrDeployedResource = new ArrayList<AbstractPlatformElement>();
        }
        return this.deployedComponentOrDeployedResource;
    }

}
