//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.platform;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.schema.spec.kdm._1_1.platform package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Requires_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Requires");
    private final static QName _ResourceType_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "ResourceType");
    private final static QName _PlatformRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "PlatformRelationship");
    private final static QName _MessagingResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "MessagingResource");
    private final static QName _DeployedSoftwareSystem_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "DeployedSoftwareSystem");
    private final static QName _PlatformAction_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "PlatformAction");
    private final static QName _AbstractPlatformElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "AbstractPlatformElement");
    private final static QName _StreamResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "StreamResource");
    private final static QName _WritesResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "WritesResource");
    private final static QName _ExternalActor_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "ExternalActor");
    private final static QName _ManagesResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "ManagesResource");
    private final static QName _RuntimeResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "RuntimeResource");
    private final static QName _LockResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "LockResource");
    private final static QName _Machine_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Machine");
    private final static QName _Loads_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Loads");
    private final static QName _ExecutionResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "ExecutionResource");
    private final static QName _PlatformElement_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "PlatformElement");
    private final static QName _MarshalledResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "MarshalledResource");
    private final static QName _Process_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Process");
    private final static QName _ReadsResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "ReadsResource");
    private final static QName _Spawns_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Spawns");
    private final static QName _PlatformEvent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "PlatformEvent");
    private final static QName _BindsTo_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "BindsTo");
    private final static QName _Thread_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "Thread");
    private final static QName _FileResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "FileResource");
    private final static QName _DataManager_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "DataManager");
    private final static QName _AbstractPlatformRelationship_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "AbstractPlatformRelationship");
    private final static QName _PlatformModel_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "PlatformModel");
    private final static QName _DeployedResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "DeployedResource");
    private final static QName _DeployedComponent_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "DeployedComponent");
    private final static QName _DefinedBy_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "DefinedBy");
    private final static QName _NamingResource_QNAME = new QName("http://schema.omg.org/spec/KDM/1.1/platform", "NamingResource");
    private final static QName _BindsToTo_QNAME = new QName("", "to");
    private final static QName _BindsToFrom_QNAME = new QName("", "from");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.schema.spec.kdm._1_1.platform
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeployedSoftwareSystem }
     * 
     */
    public DeployedSoftwareSystem createDeployedSoftwareSystem() {
        return new DeployedSoftwareSystem();
    }

    /**
     * Create an instance of {@link PlatformRelationship }
     * 
     */
    public PlatformRelationship createPlatformRelationship() {
        return new PlatformRelationship();
    }

    /**
     * Create an instance of {@link FileResource }
     * 
     */
    public FileResource createFileResource() {
        return new FileResource();
    }

    /**
     * Create an instance of {@link BindsTo }
     * 
     */
    public BindsTo createBindsTo() {
        return new BindsTo();
    }

    /**
     * Create an instance of {@link PlatformModel }
     * 
     */
    public PlatformModel createPlatformModel() {
        return new PlatformModel();
    }

    /**
     * Create an instance of {@link MarshalledResource }
     * 
     */
    public MarshalledResource createMarshalledResource() {
        return new MarshalledResource();
    }

    /**
     * Create an instance of {@link DeployedComponent }
     * 
     */
    public DeployedComponent createDeployedComponent() {
        return new DeployedComponent();
    }

    /**
     * Create an instance of {@link MessagingResource }
     * 
     */
    public MessagingResource createMessagingResource() {
        return new MessagingResource();
    }

    /**
     * Create an instance of {@link StreamResource }
     * 
     */
    public StreamResource createStreamResource() {
        return new StreamResource();
    }

    /**
     * Create an instance of {@link Loads }
     * 
     */
    public Loads createLoads() {
        return new Loads();
    }

    /**
     * Create an instance of {@link LockResource }
     * 
     */
    public LockResource createLockResource() {
        return new LockResource();
    }

    /**
     * Create an instance of {@link PlatformElement }
     * 
     */
    public PlatformElement createPlatformElement() {
        return new PlatformElement();
    }

    /**
     * Create an instance of {@link WritesResource }
     * 
     */
    public WritesResource createWritesResource() {
        return new WritesResource();
    }

    /**
     * Create an instance of {@link Machine }
     * 
     */
    public Machine createMachine() {
        return new Machine();
    }

    /**
     * Create an instance of {@link NamingResource }
     * 
     */
    public NamingResource createNamingResource() {
        return new NamingResource();
    }

    /**
     * Create an instance of {@link ReadsResource }
     * 
     */
    public ReadsResource createReadsResource() {
        return new ReadsResource();
    }

    /**
     * Create an instance of {@link PlatformAction }
     * 
     */
    public PlatformAction createPlatformAction() {
        return new PlatformAction();
    }

    /**
     * Create an instance of {@link ManagesResource }
     * 
     */
    public ManagesResource createManagesResource() {
        return new ManagesResource();
    }

    /**
     * Create an instance of {@link PlatformEvent }
     * 
     */
    public PlatformEvent createPlatformEvent() {
        return new PlatformEvent();
    }

    /**
     * Create an instance of {@link DefinedBy }
     * 
     */
    public DefinedBy createDefinedBy() {
        return new DefinedBy();
    }

    /**
     * Create an instance of {@link Spawns }
     * 
     */
    public Spawns createSpawns() {
        return new Spawns();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link Thread }
     * 
     */
    public Thread createThread() {
        return new Thread();
    }

    /**
     * Create an instance of {@link Requires }
     * 
     */
    public Requires createRequires() {
        return new Requires();
    }

    /**
     * Create an instance of {@link RuntimeResource }
     * 
     */
    public RuntimeResource createRuntimeResource() {
        return new RuntimeResource();
    }

    /**
     * Create an instance of {@link ExternalActor }
     * 
     */
    public ExternalActor createExternalActor() {
        return new ExternalActor();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link DeployedResource }
     * 
     */
    public DeployedResource createDeployedResource() {
        return new DeployedResource();
    }

    /**
     * Create an instance of {@link DataManager }
     * 
     */
    public DataManager createDataManager() {
        return new DataManager();
    }

    /**
     * Create an instance of {@link ExecutionResource }
     * 
     */
    public ExecutionResource createExecutionResource() {
        return new ExecutionResource();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Requires }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Requires")
    public JAXBElement<Requires> createRequires(Requires value) {
        return new JAXBElement<Requires>(_Requires_QNAME, Requires.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "ResourceType")
    public JAXBElement<ResourceType> createResourceType(ResourceType value) {
        return new JAXBElement<ResourceType>(_ResourceType_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlatformRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "PlatformRelationship")
    public JAXBElement<PlatformRelationship> createPlatformRelationship(PlatformRelationship value) {
        return new JAXBElement<PlatformRelationship>(_PlatformRelationship_QNAME, PlatformRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessagingResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "MessagingResource")
    public JAXBElement<MessagingResource> createMessagingResource(MessagingResource value) {
        return new JAXBElement<MessagingResource>(_MessagingResource_QNAME, MessagingResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployedSoftwareSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "DeployedSoftwareSystem")
    public JAXBElement<DeployedSoftwareSystem> createDeployedSoftwareSystem(DeployedSoftwareSystem value) {
        return new JAXBElement<DeployedSoftwareSystem>(_DeployedSoftwareSystem_QNAME, DeployedSoftwareSystem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlatformAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "PlatformAction")
    public JAXBElement<PlatformAction> createPlatformAction(PlatformAction value) {
        return new JAXBElement<PlatformAction>(_PlatformAction_QNAME, PlatformAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPlatformElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "AbstractPlatformElement")
    public JAXBElement<AbstractPlatformElement> createAbstractPlatformElement(AbstractPlatformElement value) {
        return new JAXBElement<AbstractPlatformElement>(_AbstractPlatformElement_QNAME, AbstractPlatformElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StreamResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "StreamResource")
    public JAXBElement<StreamResource> createStreamResource(StreamResource value) {
        return new JAXBElement<StreamResource>(_StreamResource_QNAME, StreamResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WritesResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "WritesResource")
    public JAXBElement<WritesResource> createWritesResource(WritesResource value) {
        return new JAXBElement<WritesResource>(_WritesResource_QNAME, WritesResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalActor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "ExternalActor")
    public JAXBElement<ExternalActor> createExternalActor(ExternalActor value) {
        return new JAXBElement<ExternalActor>(_ExternalActor_QNAME, ExternalActor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagesResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "ManagesResource")
    public JAXBElement<ManagesResource> createManagesResource(ManagesResource value) {
        return new JAXBElement<ManagesResource>(_ManagesResource_QNAME, ManagesResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuntimeResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "RuntimeResource")
    public JAXBElement<RuntimeResource> createRuntimeResource(RuntimeResource value) {
        return new JAXBElement<RuntimeResource>(_RuntimeResource_QNAME, RuntimeResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "LockResource")
    public JAXBElement<LockResource> createLockResource(LockResource value) {
        return new JAXBElement<LockResource>(_LockResource_QNAME, LockResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Machine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Machine")
    public JAXBElement<Machine> createMachine(Machine value) {
        return new JAXBElement<Machine>(_Machine_QNAME, Machine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Loads }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Loads")
    public JAXBElement<Loads> createLoads(Loads value) {
        return new JAXBElement<Loads>(_Loads_QNAME, Loads.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "ExecutionResource")
    public JAXBElement<ExecutionResource> createExecutionResource(ExecutionResource value) {
        return new JAXBElement<ExecutionResource>(_ExecutionResource_QNAME, ExecutionResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlatformElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "PlatformElement")
    public JAXBElement<PlatformElement> createPlatformElement(PlatformElement value) {
        return new JAXBElement<PlatformElement>(_PlatformElement_QNAME, PlatformElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarshalledResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "MarshalledResource")
    public JAXBElement<MarshalledResource> createMarshalledResource(MarshalledResource value) {
        return new JAXBElement<MarshalledResource>(_MarshalledResource_QNAME, MarshalledResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Process")
    public JAXBElement<Process> createProcess(Process value) {
        return new JAXBElement<Process>(_Process_QNAME, Process.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadsResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "ReadsResource")
    public JAXBElement<ReadsResource> createReadsResource(ReadsResource value) {
        return new JAXBElement<ReadsResource>(_ReadsResource_QNAME, ReadsResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Spawns }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Spawns")
    public JAXBElement<Spawns> createSpawns(Spawns value) {
        return new JAXBElement<Spawns>(_Spawns_QNAME, Spawns.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlatformEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "PlatformEvent")
    public JAXBElement<PlatformEvent> createPlatformEvent(PlatformEvent value) {
        return new JAXBElement<PlatformEvent>(_PlatformEvent_QNAME, PlatformEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindsTo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "BindsTo")
    public JAXBElement<BindsTo> createBindsTo(BindsTo value) {
        return new JAXBElement<BindsTo>(_BindsTo_QNAME, BindsTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Thread }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "Thread")
    public JAXBElement<Thread> createThread(Thread value) {
        return new JAXBElement<Thread>(_Thread_QNAME, Thread.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "FileResource")
    public JAXBElement<FileResource> createFileResource(FileResource value) {
        return new JAXBElement<FileResource>(_FileResource_QNAME, FileResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataManager }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "DataManager")
    public JAXBElement<DataManager> createDataManager(DataManager value) {
        return new JAXBElement<DataManager>(_DataManager_QNAME, DataManager.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPlatformRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "AbstractPlatformRelationship")
    public JAXBElement<AbstractPlatformRelationship> createAbstractPlatformRelationship(AbstractPlatformRelationship value) {
        return new JAXBElement<AbstractPlatformRelationship>(_AbstractPlatformRelationship_QNAME, AbstractPlatformRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlatformModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "PlatformModel")
    public JAXBElement<PlatformModel> createPlatformModel(PlatformModel value) {
        return new JAXBElement<PlatformModel>(_PlatformModel_QNAME, PlatformModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployedResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "DeployedResource")
    public JAXBElement<DeployedResource> createDeployedResource(DeployedResource value) {
        return new JAXBElement<DeployedResource>(_DeployedResource_QNAME, DeployedResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployedComponent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "DeployedComponent")
    public JAXBElement<DeployedComponent> createDeployedComponent(DeployedComponent value) {
        return new JAXBElement<DeployedComponent>(_DeployedComponent_QNAME, DeployedComponent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinedBy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "DefinedBy")
    public JAXBElement<DefinedBy> createDefinedBy(DefinedBy value) {
        return new JAXBElement<DefinedBy>(_DefinedBy_QNAME, DefinedBy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamingResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omg.org/spec/KDM/1.1/platform", name = "NamingResource")
    public JAXBElement<NamingResource> createNamingResource(NamingResource value) {
        return new JAXBElement<NamingResource>(_NamingResource_QNAME, NamingResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = BindsTo.class)
    public JAXBElement<ResourceType> createBindsToTo(ResourceType value) {
        return new JAXBElement<ResourceType>(_BindsToTo_QNAME, ResourceType.class, BindsTo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from", scope = BindsTo.class)
    public JAXBElement<ResourceType> createBindsToFrom(ResourceType value) {
        return new JAXBElement<ResourceType>(_BindsToFrom_QNAME, ResourceType.class, BindsTo.class, value);
    }

}
