//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.28 at 06:26:00 PM MEZ 
//


package org.omg.schema.spec.kdm._1_1.source;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.omg.schema.spec.kdm._1_1.core.Element;


/**
 * <p>Java class for SourceRegion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceRegion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.omg.org/spec/KDM/1.1/core}Element">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="file" type="{http://schema.omg.org/spec/KDM/1.1/source}SourceFile"/>
 *       &lt;/choice>
 *       &lt;attribute name="startLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startPosition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endPosition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceRegion", propOrder = {
    "file"
})
public class SourceRegion
    extends Element
{

    protected List<SourceFile> file;
    @XmlAttribute
    protected String startLine;
    @XmlAttribute
    protected String startPosition;
    @XmlAttribute
    protected String endLine;
    @XmlAttribute
    protected String endPosition;
    @XmlAttribute
    protected String language;
    @XmlAttribute
    protected String path;
    @XmlAttribute(name = "file")
    protected String altFile;

    /**
     * Gets the value of the file property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceFile }
     * 
     * 
     */
    public List<SourceFile> getFile() {
        if (file == null) {
            file = new ArrayList<SourceFile>();
        }
        return this.file;
    }

    /**
     * Gets the value of the startLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartLine() {
        return startLine;
    }

    /**
     * Sets the value of the startLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartLine(String value) {
        this.startLine = value;
    }

    /**
     * Gets the value of the startPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPosition() {
        return startPosition;
    }

    /**
     * Sets the value of the startPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPosition(String value) {
        this.startPosition = value;
    }

    /**
     * Gets the value of the endLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndLine() {
        return endLine;
    }

    /**
     * Sets the value of the endLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndLine(String value) {
        this.endLine = value;
    }

    /**
     * Gets the value of the endPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPosition() {
        return endPosition;
    }

    /**
     * Sets the value of the endPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPosition(String value) {
        this.endPosition = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the altFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltFile() {
        return altFile;
    }

    /**
     * Sets the value of the altFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltFile(String value) {
        this.altFile = value;
    }

}
